import Head from 'next/head'
import Layout from '@/components/layout'



export default function Home() {

  const loggoutUser = () => {
    localStorage.removeItem('token')
    window.location.reload()
  }


  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        hello world!
      </main>
      <div>
        <button onClick={loggoutUser}>logout</button>
      </div>
    </Layout>
  )
}
