import Head from 'next/head'
import Card from '@/components/card'
import { useState, useContext, useEffect } from "react"
import { userInfoContext } from "@/src/context/userInfoContext"
import LocalStorage from '../util/localStorage'
import { GetServerSidePropsContext } from 'next'
import { clearUser, userFromRequest } from '@/src/auth/tokens'
import Header from '@/components/header'


export const getServerSideProps = async(context : GetServerSidePropsContext) => {
  const user = await userFromRequest(context.req);

  if(!user) {
    return { props : {} }
  }

  return {
      props : {
          user : user
      }
    }
}

export default function Home( props : { user? : {nickname : string} }) {

  const dummyArray = new Array(100).fill(1)
  const [images, setImages] = useState<number[]>(dummyArray)
  const { user ,setUser } = useContext(userInfoContext);

  console.log(props.user)

  const loggoutUser = () => {
      clearUser();
      LocalStorage.removeItem("token");
      LocalStorage.removeItem('user');
      window.location.reload()
  }

  return (
    <>
      <Head>
        <title>picktogram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header user={props.user}/>
      <main >
        hello world!
      </main>
      <div>
        <button onClick={loggoutUser}>logout</button>
      </div>
      <div style={{ margin : "0 auto", padding : "16px 20px", display : "grid", gridTemplateColumns : "1fr 1fr 1fr" , gap : '2rem'}}>
        {images.map((_, index) => <Card key={index} isLast={index === images.length - 1 } newLimit={()=> {
            setImages((prev) => [...prev, ...new Array(10).fill(1)])
            console.log('card end')}}/>
          )}
      </div>
    </>
  )
}
