import React from "react"
import Head from 'next/head'
import Card from '@/src/components/commons/card/card'
import Header from '@/src/components/main/components/header'
import UserMainProfile from "./components/userMainProfile"
import { FetchNextPageOptions, InfiniteQueryObserverResult } from "react-query"
import { BoardData } from "./Main.type"

export default function MainUI({
    user,
    data,
    fetchNextPage
}: {
    user : {
        nickname : string
        token : string
    },
    data : any;
    fetchNextPage : (options?: FetchNextPageOptions | undefined) => Promise<InfiniteQueryObserverResult<any, unknown>>
}) {
  return (
    <>
      <Head>
        <title>picktogram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header user={user}/>
      <div style={{backgroundColor : "#d9d9d9" , paddingTop : "20px"}}>

        <div>
          {/* 달력 */}
        </div>

        <div>
          <UserMainProfile user={user} />
          {data?.pages.map((page : {list : BoardData[]}, index : number) => (
            <React.Fragment key={index}>
              {page.list.map((post , index) => (
                <Card key={post.id} isLast={index === page.list.length -1} newLimit={() => fetchNextPage()} data={post}/>
              ))}
            </React.Fragment>
          ))}
        </div>

        <div>
          {/*  */}
        </div>

      </div>

    </>
  )
}
