import React from 'react'
import Head from 'next/head'
import Header from './layout/header'

import { useRouter } from 'next/router'
import { PropsWithChildren } from 'react'

const HIDDEN_HEADERS = [
  '/login'
]


export default function Layout( props : PropsWithChildren) {
  const router = useRouter()
  const isHiddenHeader = HIDDEN_HEADERS.includes(router.asPath)

  return (
    <div>
      <Head>
        <title>picktogram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      {!isHiddenHeader && <Header />}
      <main>{props.children}</main>
    </div>
  )
}
